name: oriflame
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
        - asset: assets/fonts/Satoshi-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Oriflame-Sans
      fonts:
        - asset: assets/fonts/Oriflame-Sans.ttf
